import { $Enums } from '@prisma/client'

export const PERSONAL_ACCOUNT_ORG_ID = '_'

export enum TextTemplateKey {
  EMAIL_HTML_TEMPLATE_GENERAL = 'EMAIL_HTML_TEMPLATE_GENERAL',

  NEW_GROUP__EMAIL_TITLE = 'NEW_GROUP__EMAIL_TITLE',
  NEW_GROUP__EMAIL_CONTENT = 'NEW_GROUP__EMAIL_CONTENT',
  NEW_GROUP__SMS_CONTENT = 'NEW_GROUP__SMS_CONTENT',
  DELETED_GROUP__EMAIL_TITLE = 'DELETED_GROUP__EMAIL_TITLE',
  DELETED_GROUP__EMAIL_CONTENT = 'DELETED_GROUP__EMAIL_CONTENT',
  DELETED_GROUP__SMS_CONTENT = 'DELETED_GROUP__SMS_CONTENT',
  GROUP_ADDED_MEMBER__EMAIL_TITLE = 'GROUP_ADDED_MEMBER__EMAIL_TITLE',
  GROUP_ADDED_MEMBER__EMAIL_CONTENT = 'GROUP_ADDED_MEMBER__EMAIL_CONTENT',
  GROUP_ADDED_MEMBER__SMS_CONTENT = 'GROUP_ADDED_MEMBER__SMS_CONTENT',
  GROUP_REMOVED_MEMBER__EMAIL_TITLE = 'GROUP_REMOVED_MEMBER__EMAIL_TITLE',
  GROUP_REMOVED_MEMBER__EMAIL_CONTENT = 'GROUP_REMOVED_MEMBER__EMAIL_CONTENT',
  GROUP_REMOVED_MEMBER__SMS_CONTENT = 'GROUP_REMOVED_MEMBER__SMS_CONTENT',

  GROUP_NEW_MEMBERSHIP_REQUEST__EMAIL_TITLE = 'GROUP_NEW_MEMBERSHIP_REQUEST__EMAIL_TITLE',
  GROUP_NEW_MEMBERSHIP_REQUEST__EMAIL_CONTENT = 'GROUP_NEW_MEMBERSHIP_REQUEST__EMAIL_CONTENT',
  GROUP_NEW_MEMBERSHIP_REQUEST__SMS_CONTENT = 'GROUP_NEW_MEMBERSHIP_REQUEST__SMS_CONTENT',
  GROUP_CANCELED_MEMBERSHIP_REQUEST__EMAIL_TITLE = 'GROUP_CANCELED_MEMBERSHIP_REQUEST__EMAIL_TITLE',
  GROUP_CANCELED_MEMBERSHIP_REQUEST__EMAIL_CONTENT = 'GROUP_CANCELED_MEMBERSHIP_REQUEST__EMAIL_CONTENT',
  GROUP_CANCELED_MEMBERSHIP_REQUEST__SMS_CONTENT = 'GROUP_CANCELED_MEMBERSHIP_REQUEST__SMS_CONTENT',
  GROUP_MEMBERSHIP_REQUEST_APPROVED__EMAIL_TITLE = 'GROUP_MEMBERSHIP_REQUEST_APPROVED__EMAIL_TITLE',
  GROUP_MEMBERSHIP_REQUEST_APPROVED__EMAIL_CONTENT = 'GROUP_MEMBERSHIP_REQUEST_APPROVED__EMAIL_CONTENT',
  GROUP_MEMBERSHIP_REQUEST_APPROVED__SMS_CONTENT = 'GROUP_MEMBERSHIP_REQUEST_APPROVED__SMS_CONTENT',
  GROUP_MEMBERSHIP_REQUEST_REJECTED__EMAIL_TITLE = 'GROUP_MEMBERSHIP_REQUEST_REJECTED__EMAIL_TITLE',
  GROUP_MEMBERSHIP_REQUEST_REJECTED__EMAIL_CONTENT = 'GROUP_MEMBERSHIP_REQUEST_REJECTED__EMAIL_CONTENT',
  GROUP_MEMBERSHIP_REQUEST_REJECTED__SMS_CONTENT = 'GROUP_MEMBERSHIP_REQUEST_REJECTED__SMS_CONTENT',

  PAYOR__EMAIL_TITLE = 'PAYOR__EMAIL_TITLE',
  PAYOR__EMAIL_CONTENT = 'PAYOR__EMAIL_CONTENT',
  PAYOR__SMS_CONTENT = 'PAYOR__SMS_CONTENT',

  SETTLED_ITEM__EMAIL_TITLE = 'SETTLED_ITEM__EMAIL_TITLE',
  SETTLED_ITEM__EMAIL_CONTENT = 'SETTLED_ITEM__EMAIL_CONTENT',
  SETTLED_ITEM__SMS_CONTENT = 'SETTLED_ITEM__SMS_CONTENT'
}

export enum ActivityLogType {
  group_create = 'group_create',
  group_update = 'group_update',
  group_upsertMembers = 'group_upsertMembers',
  groupTab_create = 'groupTab_create',
  groupTab_update = 'groupTab_update',
  groupTab_delete = 'groupTab_delete',
  message_create = 'message_create',
  message_update = 'message_update',
  message_delete = 'message_delete',
  moneyRecord_upsert = 'moneyRecord_upsert',
  moneyRecord_create = 'moneyRecord_create',
  moneyRecord_update = 'moneyRecord_update',
  moneyRecord_updateMany = 'moneyRecord_updateMany',
  moneyRecord_delete = 'moneyRecord_delete',
  groupTabSettlement_settle = 'groupTabSettlement_settle'
}

export const DEFAULT_GROUP_VISIBILITY = $Enums.GroupVisibility.secret
